version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      -1337:80
    depends_on:
      - web
  web:
    build: ./semacon_backend
    command: gunicorn semacon_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./semacon_backend/:/usr/src/semacon_backend
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - daphne
  daphne:
    build: ./semacon_backend
    command: daphne --bind 0.0.0.0:8000 -p 8002 semacon_backend.asgi
    ports:
      - 8002:8002
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=semacon

volumes:
  postgres_data:
