# Generated by Django 5.0.6 on 2024-06-05 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('niveis', models.IntegerField()),
                ('area_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
        ),
    ]
